Instead of calling clockctl_ioctl directly, lookup the cdevsw and call its d_ioctl function.  This should fix an undefined reference to `clockctlioctl' when you build a kernel that has COMPAT_50 but does not have pseudo-device clockctl.